use Android O (API 26)
Unity-Technologies/android-jni-bridge pull request #12
Opened 2017-07-26 07:53 UTC by juliusmik

* Upgrading jni bridge generation to include Android API 26.
* In API 26 there is a new method https://developer.android.com/reference/android/content/ServiceConnection.html#onBindingDied(android.content.ComponentName) added to one of the interfaces. Because of this method binding had to be changed from a static to a lazy approach.
* Including ::android::media::AudioAttributes_Builder and ::android::media::AudioFocusRequest_Builder to generated api because they both are needed since Android API 26 to request audio focus.
* removing "::jvoid Remove(const ::java::lang::String& arg0) const;" because this method is present in ::android::os::Bundle, so it would appear twice in API.h in Bundle class otherwise.

2017-07-26 11:39 UTC, bitter requested changes
I would suggest fixing the potential name collision before submitting this to mainline.

2017-07-26 11:39 UTC, bitter commented on APIGenerator.java
> +		}
If multiple classes are put in the same file you would have collisions.

2017-07-26 13:19 UTC, Over17 commented on templates/android.os.Bundle.cpp
> -::jvoid Bundle::Remove(const ::java::lang::String& arg0) const
@bitter IIRC this was added to workaround changes in latest API versions but can't remember the details - will it work if the function is now moved back in Java?

2017-07-26 13:50 UTC, bitter commented on templates/android.os.Bundle.cpp
> -::jvoid Bundle::Remove(const ::java::lang::String& arg0) const
As long as the function is emitted by the generator it should be okay.

2017-07-27 12:48 UTC, bitter approved these changes

2017-07-28 08:06 UTC, merged