Fix Application.Unload crashing on certain devices
Unity-Technologies/android-jni-bridge pull request #27
Opened 2019-03-27 15:03 UTC by NinjaKyat

Fix an issue where jni::Class instances were deleted twice due to how Unity MemoryManager works. Allow deleting these classes when needed.

Added an expanding array that will be used to track all of the objects that need to be cleaned up at some point.

Added a static cleanup method to properly dispose of class objects when needed (call before MemoryManager is shut down).

---

The crash happens because the current Class objects are scoped to the library - they will always be deleted when unloading the unity library. The class objects also have pointers to objects that are allocated on the heap. This heap is cleared/trashed when MemoryManager is unloaded. The class objects try to delete those heap objects when their memory is already wiped. This is where we crash.

Now, we have a new GlobalClass class, which allocates the Class objects on the heap. It is also responsible for disposing of those objects. We can now destroy all the Class objects before we shut down the memory manager. When unloading the unity library, GlobalClass will no longer try to destroy anything, since it will know that it's Class has already been disposed. Therefore, we will no longer crash.

2019-03-27 15:45 UTC, juliusmik commented on Proxy.cpp
> +	while (g_AllProxies.GetCount() > 0)
This looks like an infinite loop

2019-03-28 14:23 UTC, aurimasc commented
Have you measured how much of an overhead does this add?

2019-03-28 14:39 UTC, NinjaKyat commented
I'll measure and compare the startup/shutdown times before and after my changes.

2019-03-30 12:22 UTC, bitter requested changes
An expanding array is the wrong data data structure. A (double) linked list would perform much better.

2019-03-30 12:30 UTC, bitter commented
I also have concerns regarding size bloat. By templating ExpandingArray you force the compiler to inline code in all compilation units using Proxy.h or ExpandingArray.h.

2019-04-01 12:45 UTC, aurimasc commented
The performance should be profiled, rather than assumed. With expandable array you pay for memory allocation when growing, with linked list - every time (unless some smarter memory management). Plus array is more friendly to CPU cache.

2019-04-01 13:11 UTC, NinjaKyat commented
Since the current implementation handles pointers, I doubt I'm winning much with an array over a linked list.

2019-04-02 14:56 UTC, bitter commented on LinkedList.h
> +			head = new Link(obj, head);
Now that you know you only deal with Proxy and Class you can remove this heap allocation and make Class and Proxy linkable. You do this by moving the next ptr into Class and Proxy. That way you can drop Link completely.

2019-04-04 15:20 UTC, bitter approved these changes

2019-04-04 15:28 UTC, aurimasc approved these changes

2019-04-04 15:28 UTC, aurimasc commented on ExpandingArray.h
> +			pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
Why mutex is recursive? I don't see guarded methods calling each other.

2019-04-04 15:28 UTC, aurimasc commented on ExpandingArray.h
> +				biggerArray[i] = elements[i];
memcpy would probably be better.

2019-04-04 15:28 UTC, aurimasc commented on ExpandingArray.h
> +		int maxSize = 32;
Better rename this to "capacity". maxSize has a feel of hard limit, while capacity is the name used by STL containers.

2019-04-04 15:28 UTC, aurimasc commented on ExpandingArray.h
> +						elements[i] = elements[count-1];
Please add a comment that Remove() swaps the removee with last element prior to removal. Too a while for me to notice.

2019-04-04 15:28 UTC, aurimasc commented on APIHelper.cpp
> +		for (int i = 0; i < g_AllClasses.GetCount(); i++)
Wouldn't it be more efficient to iterate from the last?

2019-04-05 05:18 UTC, NinjaKyat commented on ExpandingArray.h
> +			pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
CleanupAll calls into Cleanup which tries to remove the object from the list.

2019-04-05 05:18 UTC, NinjaKyat commented on ExpandingArray.h
> +				biggerArray[i] = elements[i];
This code no longer exists

2019-04-05 05:19 UTC, NinjaKyat commented on ExpandingArray.h
> +		int maxSize = 32;
Ditto, code is no longer valid.

2019-04-05 05:21 UTC, NinjaKyat commented
@aurimasc you seem to have reviewed some of the older code, most of which got thrown out. Is the new code okay?

2019-04-05 10:16 UTC, merged